services:
  - type: web
    name: hommiespace-api-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build --workspace=apps/api
    startCommand: node apps/api/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
