services:
  - type: web
    name: hommiespace-api-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build --workspace=@hommiespace/shared && npm run build --workspace=@hommiespace/api
    startCommand: node apps/api/dist/app.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
